### ISSUE TITLE
[Feature] - Refactor and evolve schema application example

### ISSUE THREAD

**Issue by Hafflgav** [Miragon/consulting#26]
- [x] Description created
- [x] Reviewed by peer: @DaAnda97 
- [ ] Prioritised

# Description
We want to implement a running schema application to reflect the current state of Miranum Platform. 

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Update Schema Application Example 
- [ ] Make sure to update its readme accordingly
```

**Comment by lmoesle** [comment]
@Hafflgav Is this issue still needed?

**Comment by Hafflgav** [comment]
Given that this issue has been created quite a while ago, I do not think this is required anymore.
